/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
import { Pokemon } from "./components/molecules/pokemon-details/pokemon-details";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface PokemonButton {
        "text": string;
        "url": string;
    }
    interface PokemonDetails {
        "pokemon": Pokemon;
    }
    interface PokemonError {
    }
    interface PokemonHeader {
    }
    interface PokemonImage {
        "src": string;
    }
    interface PokemonParagraph {
        "text": string;
    }
    interface PokemonSpinner {
        "text": string;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPokemonButtonElement extends Components.PokemonButton, HTMLStencilElement {
    }
    var HTMLPokemonButtonElement: {
        prototype: HTMLPokemonButtonElement;
        new (): HTMLPokemonButtonElement;
    };
    interface HTMLPokemonDetailsElement extends Components.PokemonDetails, HTMLStencilElement {
    }
    var HTMLPokemonDetailsElement: {
        prototype: HTMLPokemonDetailsElement;
        new (): HTMLPokemonDetailsElement;
    };
    interface HTMLPokemonErrorElement extends Components.PokemonError, HTMLStencilElement {
    }
    var HTMLPokemonErrorElement: {
        prototype: HTMLPokemonErrorElement;
        new (): HTMLPokemonErrorElement;
    };
    interface HTMLPokemonHeaderElement extends Components.PokemonHeader, HTMLStencilElement {
    }
    var HTMLPokemonHeaderElement: {
        prototype: HTMLPokemonHeaderElement;
        new (): HTMLPokemonHeaderElement;
    };
    interface HTMLPokemonImageElement extends Components.PokemonImage, HTMLStencilElement {
    }
    var HTMLPokemonImageElement: {
        prototype: HTMLPokemonImageElement;
        new (): HTMLPokemonImageElement;
    };
    interface HTMLPokemonParagraphElement extends Components.PokemonParagraph, HTMLStencilElement {
    }
    var HTMLPokemonParagraphElement: {
        prototype: HTMLPokemonParagraphElement;
        new (): HTMLPokemonParagraphElement;
    };
    interface HTMLPokemonSpinnerElement extends Components.PokemonSpinner, HTMLStencilElement {
    }
    var HTMLPokemonSpinnerElement: {
        prototype: HTMLPokemonSpinnerElement;
        new (): HTMLPokemonSpinnerElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "pokemon-button": HTMLPokemonButtonElement;
        "pokemon-details": HTMLPokemonDetailsElement;
        "pokemon-error": HTMLPokemonErrorElement;
        "pokemon-header": HTMLPokemonHeaderElement;
        "pokemon-image": HTMLPokemonImageElement;
        "pokemon-paragraph": HTMLPokemonParagraphElement;
        "pokemon-spinner": HTMLPokemonSpinnerElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface PokemonButton {
        "text": string;
        "url": string;
    }
    interface PokemonDetails {
        "pokemon"?: Pokemon;
    }
    interface PokemonError {
    }
    interface PokemonHeader {
    }
    interface PokemonImage {
        "src": string;
    }
    interface PokemonParagraph {
        "text"?: string;
    }
    interface PokemonSpinner {
        "text"?: string;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "pokemon-button": PokemonButton;
        "pokemon-details": PokemonDetails;
        "pokemon-error": PokemonError;
        "pokemon-header": PokemonHeader;
        "pokemon-image": PokemonImage;
        "pokemon-paragraph": PokemonParagraph;
        "pokemon-spinner": PokemonSpinner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "pokemon-button": LocalJSX.PokemonButton & JSXBase.HTMLAttributes<HTMLPokemonButtonElement>;
            "pokemon-details": LocalJSX.PokemonDetails & JSXBase.HTMLAttributes<HTMLPokemonDetailsElement>;
            "pokemon-error": LocalJSX.PokemonError & JSXBase.HTMLAttributes<HTMLPokemonErrorElement>;
            "pokemon-header": LocalJSX.PokemonHeader & JSXBase.HTMLAttributes<HTMLPokemonHeaderElement>;
            "pokemon-image": LocalJSX.PokemonImage & JSXBase.HTMLAttributes<HTMLPokemonImageElement>;
            "pokemon-paragraph": LocalJSX.PokemonParagraph & JSXBase.HTMLAttributes<HTMLPokemonParagraphElement>;
            "pokemon-spinner": LocalJSX.PokemonSpinner & JSXBase.HTMLAttributes<HTMLPokemonSpinnerElement>;
        }
    }
}
